import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material'

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatButtonModule,
    Material.MatIconModule,
    Material.MatTableModule,
    Material.MatDividerModule,
    Material.MatCardModule,
    Material.MatSelectModule,
    Material.MatDialogModule,
    Material.MatAutocompleteModule,
    Material.MatButtonToggleModule,
    Material.MatChipsModule,
    Material.MatDialogModule,
    Material.MatExpansionModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRippleModule,
    Material.MatSortModule,
    Material.MatProgressBarModule,
    Material.MatSnackBarModule,
  ],
  exports : [
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatButtonModule,
    Material.MatIconModule,
    Material.MatTableModule,
    Material.MatDividerModule,
    Material.MatCardModule,
    Material.MatSelectModule,
    Material.MatDialogModule,
    Material.MatAutocompleteModule,
    Material.MatButtonToggleModule,
    Material.MatChipsModule,
    Material.MatDialogModule,
    Material.MatExpansionModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRippleModule,
    Material.MatSortModule,
    Material.MatProgressBarModule,
    Material.MatSnackBarModule,
  ]
})
export class MaterialModule { }
